#!/bin/bash

set -e
DOCKER_IMAGE=$1

uid=$(id -u)
docker run \
    -it \
    -e DISPLAY=$DISPLAY \
    --privileged \
    --network host \
    --device /dev/snd \
    --group-add=audio \
    --group-add $(getent group audio | cut -d: -f3) \
    --device /dev/dri \
    -v /etc/machine-id:/etc/machine-id \
    -v /var/lib/dbus:/var/lib/dbus \
    -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native \
    -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native \
    -v ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie \
    -v "$sourcedir:/opt/game/source:rw" \
    -v "${HOME}/.Xauthority:/home/loki/.Xauthority:rw" \
    -v "${HOME}/.loki:/home/loki/.loki:rw" \
    -v "${HOME}/.quake4:/home/loki/.quake4:rw" \
    -v "${HOME}/.hyperion:/home/loki/.hyperion:rw" \
    -v "/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    -v "${XDG_RUNTIME_DIR}:/run/loki/$uid:rw" \
    -v "/media/cdrom:/cdrom" \
    --env=DISPLAY \
    --env=XDG_RUNTIME_DIR=/run/user/$uid \
    ${DOCKER_FLAGS} \
    $DOCKER_IMAGE
