#!/usr/bin/env bash

set -e
DOCKER_IMAGE=$1

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    #Xephyr :1 -screen 1280x1024 -fullscreen 2> /dev/null & # 1280x1024
    Xwayland -geometry 1280x1024 :1 -fullscreen 2> /dev/null &
    X_PID=$!
    export DISPLAY=:1
    echo "PID of nexted X server: $X_PID"
fi

# This is needed because Xephyr and Xwayland don't close after the game does
# and for some reason every time new ossp-padsp process is created
# and never terminated, which after some time causes crackling.
# -9 is there bcs otherwise it doesn't want to die
cleanup(){
    echo "Performing cleanup..."
    [ ! -z "$X_PID" ] && kill "$X_PID"
    for pid in $(pidof ossp-padsp); do
        echo "Killing $pid"
        kill -9 "$pid"
    done
}

trap 'cleanup' ERR
trap 'cleanup' EXIT

uid=$(id -u)
docker run \
    -it \
    -e DISPLAY="$DISPLAY" \
    --privileged \
    --network host \
    --device /dev/snd \
    --device /dev/dri \
    --group-add=audio \
    -v /etc/machine-id:/etc/machine-id \
    -v /var/lib/dbus:/var/lib/dbus \
    -e PULSE_SERVER=unix:"${XDG_RUNTIME_DIR}/pulse/native" \
    -v "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native" \
    -v "${XDG_CONFIG_HOME:-$HOME/.config}/pulse/cookie":/home/loki/.config/pulse/cookie \
    --group-add "$(getent group audio | cut -d: -f3)" \
    -v "${XAUTHORITY:-$HOME/.Xauthority}:/home/loki/.Xauthority:rw" \
    -v "${XDG_DATA_HOME:-$HOME/.local/share}/loki:/home/loki/.loki:rw" \
    -v "${XDG_DATA_HOME:-$HOME/.local/share}/quake4:/home/loki/.quake4:rw" \
    -v "${XDG_DATA_HOME:-$HOME/.local/share}/hyperion:/home/loki/.hyperion:rw" \
    -v "/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    -v "${XDG_RUNTIME_DIR}:/run/loki/$uid:rw" \
    -v "/media/cdrom:/cdrom" \
    --env=DISPLAY \
    --env=XDG_RUNTIME_DIR="/run/user/$uid" \
    "$DOCKER_IMAGE"
