#!/bin/bash

set -e
DOCKER_IMAGE=$1

uid=$(id -u)
docker run \
    -it \
    -e DISPLAY="$DISPLAY" \
    --privileged \
    --network host \
    --device /dev/snd \
    --device /dev/dri \
    --group-add=audio \
    -v /etc/machine-id:/etc/machine-id \
    -v /var/lib/dbus:/var/lib/dbus \
    -e PULSE_SERVER=unix:"${XDG_RUNTIME_DIR}/pulse/native" \
    -v "${XDG_RUNTIME_DIR}/pulse/native":"${XDG_RUNTIME_DIR}/pulse/native" \
    -v "${XDG_CONFIG_HOME:-$HOME/.config}/pulse/cookie":/root/.config/pulse/cookie \
    --group-add "$(getent group audio | cut -d: -f3)" \
    -v "${XAUTHORITY:-$HOME/.Xauthority}:/home/loki/.Xauthority:rw" \
    -v "${XDG_DATA_HOME:-$HOME/.local/share}/loki:/home/loki/.loki:rw" \
    -v "${XDG_DATA_HOME:-$HOME/.local/share}/quake4:/home/loki/.quake4:rw" \
    -v "${XDG_DATA_HOME:-$HOME/.local/share}/hyperion:/home/loki/.hyperion:rw" \
    -v "/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    -v "${XDG_RUNTIME_DIR}:/run/loki/$uid:rw" \
    -v "/media/cdrom:/cdrom" \
    --env=DISPLAY \
    --env=XDG_RUNTIME_DIR="/run/user/$uid" \
    "$DOCKER_IMAGE"
